/** Emit src/app/themes.css from src/lib/themes.ts. Run after editing themes: pnpm exec tsx scripts/gen-themes.ts */
import { writeFileSync } from "node:fs";
import { themeCss } from "../src/lib/themes";

const out = `/* Generated by scripts/gen-themes.ts from src/lib/themes.ts. Do not edit by hand. */\n${themeCss()}\n`;
writeFileSync(new URL("../src/app/themes.css", import.meta.url), out);
console.log("wrote src/app/themes.css");
