/**
 * Writes src/lib/workflows/catalog.gen.ts: every tool's id, pack and card fields, without descriptions,
 * prompts or calculator code. Pages that list tools import this (tens of KB) instead of the registry (over 1 MB);
 * a tool's full definition is loaded when it is opened.   pnpm exec tsx scripts/gen-catalog.ts
 */
import { writeFileSync } from "node:fs";
import { CORE_PACK } from "../src/lib/workflows/packs/core";
import { BANKER_PACK } from "../src/lib/workflows/packs/banker";
import { PE_PACK } from "../src/lib/workflows/packs/pe";
import { VC_PACK } from "../src/lib/workflows/packs/vc";
import { MARKETS_PACK } from "../src/lib/workflows/packs/markets";
import { CORPFIN_PACK } from "../src/lib/workflows/packs/corpfin";
import { CONSULTANT_PACK } from "../src/lib/workflows/packs/consultant";
import { ACCOUNTANT_PACK } from "../src/lib/workflows/packs/accountant";
import { STUDENT_PACK } from "../src/lib/workflows/packs/student";
import { INFERENCE_PACK } from "../src/lib/workflows/packs/inference";
import type { ToolDef } from "../src/lib/workflows/types";

// Same order as the registry, so "first definition wins" picks the same pack.
const PACKS: [string, unknown][] = [["core", CORE_PACK], ["banker", BANKER_PACK], ["pe", PE_PACK], ["vc", VC_PACK], ["markets", MARKETS_PACK], ["corpfin", CORPFIN_PACK], ["consultant", CONSULTANT_PACK], ["accountant", ACCOUNTANT_PACK], ["student", STUDENT_PACK], ["inference", INFERENCE_PACK]];

const seen = new Set<string>();
const rows: Record<string, unknown>[] = [];
for (const [pack, list] of PACKS) {
  if (!Array.isArray(list)) continue;
  for (const t of list as ToolDef[]) {
    if (!t?.id || seen.has(t.id)) continue;
    seen.add(t.id);
    rows.push({
      id: t.id, kind: t.kind, pack, title: t.title, tagline: t.tagline, roles: t.roles,
      ...(t.specialties ? { specialties: t.specialties } : {}), category: t.category, icon: t.icon,
      ...(t.tags?.length ? { tags: t.tags } : {}), ...(t.savesMinutes ? { savesMinutes: t.savesMinutes } : {}),
    });
  }
}
const body = `// Generated by scripts/gen-catalog.ts from the tool packs. Do not edit by hand.
import type { ToolMeta } from "./catalog";

export const TOOL_CATALOG: ToolMeta[] = ${JSON.stringify(rows, null, 0).replace(/\},\{/g, "},\n  {").replace(/^\[\{/, "[\n  {").replace(/\}\]$/, "},\n]")};
`;
writeFileSync(new URL("../src/lib/workflows/catalog.gen.ts", import.meta.url), body);
console.log(`catalog: ${rows.length} tools`);
